"""Cloud owner credentials and locators excluded from measurement children."""
CLOUD_SECRET_ENV = frozenset({
    'VAST_SEAFILE_UPLOAD_LINK', 'VAST_SEAFILE_READ_LINK',
    'AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY', 'AWS_SESSION_TOKEN', 'AWS_SECURITY_TOKEN',
    'AWS_PROFILE', 'AWS_DEFAULT_PROFILE', 'AWS_SHARED_CREDENTIALS_FILE', 'AWS_CONFIG_FILE',
    'VAST_S3_CREDENTIALS_FILE', 'AWS_CONTAINER_CREDENTIALS_RELATIVE_URI',
    'AWS_CONTAINER_CREDENTIALS_FULL_URI', 'AWS_CONTAINER_AUTHORIZATION_TOKEN',
    'AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE', 'AWS_WEB_IDENTITY_TOKEN_FILE',
    'AWS_ROLE_ARN', 'AWS_ROLE_SESSION_NAME', 'AWS_ENDPOINT_URL', 'AWS_ENDPOINT_URL_S3',
})
